name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      
      - name: Install dependencies
        run: npm install

      
      - name: Build project
        run: npm run build

      
      - name: Run ESLint
        run: npm run lint

      
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: npx netlify deploy --prod --dir=dist

      
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://gitlab.com/Geliogena/news_servis2.git
          git push gitlab main
